language: php
php:
  - 7.1
  - 7.2

services:
  - redis-server

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; pecl install memcached; fi; 
  - if [[ $TRAVIS_PHP_VERSION = 7.2 ]] ; then pecl config-set preferred_state beta; echo yes | pecl install apcu; pecl install memcached; fi; 
  - phpenv config-add tests/php.ini
  - composer install
script: 
  - composer build 
