dist: xenial

language: php
php:
  - 7.1
  - 7.2
  - 7.3

cache: 
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - redis-server
  - memcached

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-add tests/php.ini

install:
  - composer install
script: 
  - composer build 
