language: php
php:
  - 7.1
  - 7.2
  - 7.3

cache: 
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - redis-server

before_script:
  - pecl config-set preferred_state beta
  - echo yes | pecl install apcu 
  - echo yes | pecl install memcached 
  - phpenv config-add tests/php.ini

install:
  - composer install
script: 
  - composer build 
