language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - redis-server
before_script:
  - pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ;
  - phpenv config-add tests/php.ini
  - composer install
script: cd tests && phpunit --configuration phpunit.xml --coverage-text ./
